#!/bin/sh
set -e

# Generate Secrets.xcconfig from Xcode Cloud environment variables.
# Add each variable in App Store Connect → Xcode Cloud → Workflow → Environment Variables.

cat > "$CI_PRIMARY_REPOSITORY_PATH/IBBLB/Secrets.xcconfig" << EOF
// Secrets.xcconfig - Generated by ci_post_clone.sh
// DO NOT COMMIT THIS FILE

SUPABASE_URL = ${SUPABASE_URL}
SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"

SANITY_PROJECT_ID = ${SANITY_PROJECT_ID}
SANITY_DATASET = ${SANITY_DATASET}

CERT_PIN_SUPABASE = ${CERT_PIN_SUPABASE}
CERT_PIN_SANITY = ${CERT_PIN_SANITY}
CERT_PIN_YOUTUBE = ${CERT_PIN_YOUTUBE}
CERT_PIN_VERCEL = ${CERT_PIN_VERCEL}
EOF

echo "✅ Secrets.xcconfig generated"
